### ISSUE TITLE
Marketboard Error Messages

### ISSUE THREAD

**Issue by xPumaa** [chalkos/Marketbuddy#12]
### What are you trying to do?

Buying items on the marketboard.

### What is the expected behavior?

No error message.

### What actually happened?

After clicking on an item to buy it, an error message is thrown in the chat.

Error message:
[2:19][Marketbuddy] Error getting price per item or setting the new price. Use /xllog to see the error and submit it in a github issue

### Suggested solution

Price check only for retainers

### Logs

```shell
--------------------------------
02:20:27.465 | ERR [Marketbuddy] Error getting price per item or setting the new price
System.NullReferenceException: Object reference not set to an instance of an object.
   at Marketbuddy.MarketGuiEventHandler.SetPrice(Int32 newPrice) in C:\Users\chalkos\Software\ffxiv\Marketbuddy\Marketbuddy\MarketGuiEventHandler.cs:line 210
   at Marketbuddy.MarketGuiEventHandler.AddonItemSearchResult_ReceiveEvent_Delegate_Detour(IntPtr self, UInt16 eventType, UInt32 eventParam, IntPtr eventStruct, IntPtr nodeParam) in C:\Users\chalkos\Software\ffxiv\Marketbuddy\Marketbuddy\MarketGuiEventHandler.cs:line 196
--------------------------------
```

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and Marketbuddy.

**Comment by chalkos** [comment]
Thanks. the error should be gone now
