### ISSUE TITLE
Also a Market Board Error

### ISSUE THREAD

**Issue by joshboston723** [chalkos/Marketbuddy#13]
### What are you trying to do?

Buying a Pactmaker's Spinning Wheel (HQ)

### What is the expected behavior?

Not seeing an error

### What actually happened?

[20:41][Marketbuddy] Error getting price per item or setting the new price. Use /xllog to see the error and submit it in a github issue

### Suggested solution

I don't know, the log told me to post it on github

### Logs

```shell
--------------------------------
20:41:13.169 | ERR [Marketbuddy] Error getting price per item or setting the new price
System.NullReferenceException: Object reference not set to an instance of an object.
   at Marketbuddy.MarketGuiEventHandler.SetPrice(Int32 newPrice) in C:\Users\chalkos\Software\ffxiv\Marketbuddy\Marketbuddy\MarketGuiEventHandler.cs:line 210
   at Marketbuddy.MarketGuiEventHandler.AddonItemSearchResult_ReceiveEvent_Delegate_Detour(IntPtr self, UInt16 eventType, UInt32 eventParam, IntPtr eventStruct, IntPtr nodeParam) in C:\Users\chalkos\Software\ffxiv\Marketbuddy\Marketbuddy\MarketGuiEventHandler.cs:line 196
{ } [ Send ]
```

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and Marketbuddy.

**Comment by xPumaa** [comment]
Is the same error as in #12

**Comment by chalkos** [comment]
Thanks. the error should be gone now
