### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by nanol1st** [chalkos/Marketbuddy#21]
started getting this error today. Already restarted game.

![image](https://user-images.githubusercontent.com/107891839/174681320-0f08953f-35b7-4ebe-b7f0-0eb43802fbe9.png)

**Comment by xPumaa** [comment]
Can you post the error message from /xllog when you install the plugin?

**Comment by nanol1st** [comment]
--------------------------------
17:40:46.690 | INF [PLUGINM] Installed plugin Marketbuddy (testing=False)
--------------------------------
17:40:46.690 | INF [PLUGINM] Loading plugin Marketbuddy
--------------------------------
17:40:46.750 | INF [LOCALPLUGIN] Loading Marketbuddy.dll
--------------------------------
17:40:46.752 | ERR [LOCALPLUGIN] Error while loading Marketbuddy
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.MissingMethodException: Method not found: 'Void FFXIVClientStructs.Resolver.Initialize()'.
   at Marketbuddy.Marketbuddy..ctor(DalamudPluginInterface pluginInterface)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Dalamud.IoC.Internal.ServiceContainer.Create(Type objectType, Object[] scopedObjects)
   at Dalamud.Plugin.Internal.Types.LocalPlugin.Load(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Types\LocalPlugin.cs:line 337
--------------------------------
17:40:46.754 | ERR [PLUGINW] Plugin installer threw an unexpected error
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.MissingMethodException: Method not found: 'Void FFXIVClientStructs.Resolver.Initialize()'.
   at Marketbuddy.Marketbuddy..ctor(DalamudPluginInterface pluginInterface)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Dalamud.IoC.Internal.ServiceContainer.Create(Type objectType, Object[] scopedObjects)
   at Dalamud.Plugin.Internal.Types.LocalPlugin.Load(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Types\LocalPlugin.cs:line 337
   at Dalamud.Plugin.Internal.PluginManager.LoadPlugin(FileInfo dllFile, LocalPluginManifest manifest, PluginLoadReason reason, Boolean isDev, Boolean isBoot, Boolean doNotLoad) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\PluginManager.cs:line 657
   at Dalamud.Plugin.Internal.PluginManager.InstallPluginAsync(RemotePluginManifest repoManifest, Boolean useTesting, PluginLoadReason reason) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\PluginManager.cs:line 575
{ } [ Send ]

**Comment by xPumaa** [comment]
@chalkos, to me it sounds like a problem with dalamud itself or an incompatibility with another plugin.

For readability in a code block:
```17:40:46.690 | INF [PLUGINM] Installed plugin Marketbuddy (testing=False)
17:40:46.690 | INF [PLUGINM] Loading plugin Marketbuddy
17:40:46.750 | INF [LOCALPLUGIN] Loading Marketbuddy.dll
17:40:46.752 | ERR [LOCALPLUGIN] Error while loading Marketbuddy
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> System.MissingMethodException: Method not found: 'Void FFXIVClientStructs.Resolver.Initialize()'.
at Marketbuddy.Marketbuddy..ctor(DalamudPluginInterface pluginInterface)
--- End of inner exception stack trace ---
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
at System.Reflection.RuntimeConstructorInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at Dalamud.IoC.Internal.ServiceContainer.Create(Type objectType, Object[] scopedObjects)
at Dalamud.Plugin.Internal.Types.LocalPlugin.Load(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Types\LocalPlugin.cs:line 337
17:40:46.754 | ERR [PLUGINW] Plugin installer threw an unexpected error
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> System.MissingMethodException: Method not found: 'Void FFXIVClientStructs.Resolver.Initialize()'.
at Marketbuddy.Marketbuddy..ctor(DalamudPluginInterface pluginInterface)
--- End of inner exception stack trace ---
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
at System.Reflection.RuntimeConstructorInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at Dalamud.IoC.Internal.ServiceContainer.Create(Type objectType, Object[] scopedObjects)
at Dalamud.Plugin.Internal.Types.LocalPlugin.Load(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Types\LocalPlugin.cs:line 337
at Dalamud.Plugin.Internal.PluginManager.LoadPlugin(FileInfo dllFile, LocalPluginManifest manifest, PluginLoadReason reason, Boolean isDev, Boolean isBoot, Boolean doNotLoad) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\PluginManager.cs:line 657
at Dalamud.Plugin.Internal.PluginManager.InstallPluginAsync(RemotePluginManifest repoManifest, Boolean useTesting, PluginLoadReason reason) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\PluginManager.cs:line 575
{ } [ Send ]
```

**Comment by nanol1st** [comment]
Did a fresh dalamud install and now it's working again. thanks for the help 👍

**Comment by chalkos** [comment]
Version 0.2.2.12 should fix this.
thanks @xPumaa !
