### ISSUE TITLE
Market buddy crashing

### ISSUE THREAD

**Issue by Blissyboo** [chalkos/Marketbuddy#31]
### What are you trying to do?

When i open my retainers selling menu to try and change a price of an item the game hard crashes and locks up. When the plugin is disabled nothing causes the crash but because dalumud doesn't tell you if a plugin conflicts with another idk what is causing it.

### What is the expected behavior?

The plugin should open the search history of any item you try to sell through retainers and show previous history of sales

### What actually happened?

Game just hard crashes the moment you try to put anything up for sale

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and Marketbuddy.

**Comment by Kavochevo** [comment]
Have the same problem too.

**Comment by xPumaa** [comment]
Can you look at the log after logging in with `/xllog`?
What happens if you try to open the marketbuddy config with `/mbuddy`?

**Comment by Kavochevo** [comment]
In /xllog I have non-stop spamming this error exeption:
```
ERR Exception during raise of "Void DrawUi()"
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Newtonsoft.Json.JsonReaderException: Input string '1.0' is not a valid integer. Path 'UndercutPrice', line 20, position 22.
   at Newtonsoft.Json.JsonTextReader.ParseReadNumber(ReadType readType, Char firstChar, Int32 initialPosition)
   at Newtonsoft.Json.JsonTextReader.ReadNumberValue(ReadType readType)
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Dalamud.Configuration.PluginConfigurations.LoadForType[T](String pluginName) in C:\goatsoft\companysecrets\dalamud\Configuration\PluginConfigurations.cs:line 103
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Dalamud.Plugin.DalamudPluginInterface.GetPluginConfig() in C:\goatsoft\companysecrets\dalamud\Plugin\DalamudPluginInterface.cs:line 314
   at Marketbuddy.Configuration.GetOrLoad() in C:\Users\chalkos\Software\ffxiv\Marketbuddy\Marketbuddy\Configuration.cs:line 62
   at Marketbuddy.PluginUI.DrawSettingsWindow() in C:\Users\chalkos\Software\ffxiv\Marketbuddy\Marketbuddy\PluginUI.cs:line 88
   at Marketbuddy.Marketbuddy.DrawUi() in C:\Users\chalkos\Software\ffxiv\Marketbuddy\Marketbuddy\Marketbuddy.cs:line 84
   at Dalamud.Utility.EventHandlerExtensions.HandleInvoke(Action act) in C:\goatsoft\companysecrets\dalamud\Utility\EventHandlerExtensions.cs:line 96
```

And when I open mbaddy config, there's just a tine little square
![image](https://user-images.githubusercontent.com/69363472/211283301-f7f88c13-9d24-48a4-915b-50d5dff5291b.png)

**Comment by fipbento** [comment]
Ohh the window!! I have the same problem too!

**Comment by xPumaa** [comment]
That's what I thought.
The easiest way to fix this problem is to reset the configuration. Go to the plugin installer, right-click MarketBuddy and then click on "Reset plugin configuration and reload". With this option you have to reconfigure the plugin.

You can also disable MarketBuddy, then go to `%appdata%\XIVLauncher\pluginConfigs` in your explorer and edit the file `Marketbuddy.json`. There is a line with `UndercutPrice: 1.0`, change it to `UndercutPrice: 1` and save. Activate the plugin again and everything should work.

**Comment by Kavochevo** [comment]
It works! "Reset plugin configuration and reload" solved the problem, thank you <3

**Comment by fipbento** [comment]
It worked for me too! Thank you so much!
