### ISSUE TITLE
Crash from recent update for patch

### ISSUE THREAD

**Issue by iRobsie** [chalkos/Marketbuddy#34]
### What are you trying to do?

Use the plugin

### What is the expected behavior?

It work

### What actually happened?

Game Crashes (and fills the .log file up VERY fast.

### Logs

```shell
2023-01-16 06:21:53.225 -06:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyMy0wMS0xNlQwNjoyMTo1My4yMjUyNjkyLTA2OjAwIiwiSW5mbyI6IlN5c3RlbS5SZWZsZWN0aW9uLlRhcmdldEludm9jYXRpb25FeGNlcHRpb246IEV4Y2VwdGlvbiBoYXMgYmVlbiB0aHJvd24gYnkgdGhlIHRhcmdldCBvZiBhbiBpbnZvY2F0aW9uLlxyXG4gLS0tPiBOZXd0b25zb2Z0Lkpzb24uSnNvblJlYWRlckV4Y2VwdGlvbjogSW5wdXQgc3RyaW5nICcxLjAnIGlzIG5vdCBhIHZhbGlkIGludGVnZXIuIFBhdGggJ1VuZGVyY3V0UHJpY2UnLCBsaW5lIDIwLCBwb3NpdGlvbiAyMi5cclxuICAgYXQgTmV3dG9uc29mdC5Kc29uLkpzb25UZXh0UmVhZGVyLlBhcnNlUmVhZE51bWJlcihSZWFkVHlwZSByZWFkVHlwZSwgQ2hhciBmaXJzdENoYXIsIEludDMyIGluaXRpYWxQb3NpdGlvbilcclxuICAgYXQgTmV3dG9uc29mdC5Kc29uLkpzb25UZXh0UmVhZGVyLlJlYWROdW1iZXJWYWx1ZShSZWFkVHlwZSByZWFkVHlwZSlcclxuICAgYXQgTmV3dG9uc29mdC5Kc29uLkpzb25SZWFkZXIuUmVhZEZvclR5cGUoSnNvbkNvbnRyYWN0IGNvbnRyYWN0LCBCb29sZWFuIGhhc0NvbnZlcnRlcilcclxuICAgYXQgTmV3dG9uc29mdC5Kc29uLlNlcmlhbGl6YXRpb24uSnNvblNlcmlhbGl6ZXJJbnRlcm5hbFJlYWRlci5Qb3B1bGF0ZU9iamVjdChPYmplY3QgbmV3T2JqZWN0LCBKc29uUmVhZGVyIHJlYWRlciwgSnNvbk9iamVjdENvbnRyYWN0IGNvbnRyYWN0LCBKc29uUHJvcGVydHkgbWVtYmVyLCBTdHJpbmcgaWQpXHJcbiAgIGF0IE5ld3RvbnNvZnQuSnNvbi5TZXJpYWxpemF0aW9uLkpzb25TZXJpYWxpemVySW50ZXJuYWxSZWFkZXIuQ3JlYXRlT2JqZWN0KEpzb25SZWFkZXIgcmVhZGVyLCBUeXBlIG9iamVjdFR5cGUsIEpzb25Db250cmFjdCBjb250cmFjdCwgSnNvblByb3BlcnR5IG1lbWJlciwgSnNvbkNvbnRhaW5lckNvbnRyYWN0IGNvbnRhaW5lckNvbnRyYWN0LCBKc29uUHJvcGVydHkgY29udGFpbmVyTWVtYmVyLCBPYmplY3QgZXhpc3RpbmdWYWx1ZSlcclxuICAgYXQgTmV3dG9uc29mdC5Kc29uLlNlcmlhbGl6YXRpb24uSnNvblNlcmlhbGl6ZXJJbnRlcm5hbFJlYWRlci5DcmVhdGVWYWx1ZUludGVybmFsKEpzb25SZWFkZXIgcmVhZGVyLCBUeXBlIG9iamVjdFR5cGUsIEpzb25Db250cmFjdCBjb250cmFjdCwgSnNvblByb3BlcnR5IG1lbWJlciwgSnNvbkNvbnRhaW5lckNvbnRyYWN0IGNvbnRhaW5lckNvbnRyYWN0LCBKc29uUHJvcGVydHkgY29udGFpbmVyTWVtYmVyLCBPYmplY3QgZXhpc3RpbmdWYWx1ZSlcclxuICAgYXQgTmV3dG9uc29mdC5Kc29uLlNlcmlhbGl6YXRpb24uSnNvblNlcmlhbGl6ZXJJbnRlcm5hbFJlYWRlci5EZXNlcmlhbGl6ZShKc29uUmVhZGVyIHJlYWRlciwgVHlwZSBvYmplY3RUeXBlLCBCb29sZWFuIGNoZWNrQWRkaXRpb25hbENvbnRlbnQpXHJcbiAgIGF0IE5ld3RvbnNvZnQuSnNvbi5Kc29uQ29udmVydC5EZXNlcmlhbGl6ZU9iamVjdChTdHJpbmcgdmFsdWUsIFR5cGUgdHlwZSwgSnNvblNlcmlhbGl6ZXJTZXR0aW5ncyBzZXR0aW5ncylcclxuICAgYXQgTmV3dG9uc29mdC5Kc29uLkpzb25Db252ZXJ0LkRlc2VyaWFsaXplT2JqZWN0W1RdKFN0cmluZyB2YWx1ZSwgSnNvblNlcmlhbGl6ZXJTZXR0aW5ncyBzZXR0aW5ncylcclxuICAgYXQgRGFsYW11ZC5Db25maWd1cmF0aW9uLlBsdWdpbkNvbmZpZ3VyYXRpb25zLkxvYWRGb3JUeXBlW1RdKFN0cmluZyBwbHVnaW5OYW1lKSBpbiBDOlxcZ29hdHNvZnRcXGNvbXBhbnlzZWNyZXRzXFxkYWxhbXVkXFxDb25maWd1cmF0aW9uXFxQbHVnaW5Db25maWd1cmF0aW9ucy5jczpsaW5lIDEwM1xyXG4gICBhdCBJbnZva2VTdHViX1BsdWdpbkNvbmZpZ3VyYXRpb25zLkxvYWRGb3JUeXBlKE9iamVjdCwgT2JqZWN0LCBJbnRQdHIqKVxyXG4gICBhdCBTeXN0ZW0uUmVmbGVjdGlvbi5NZXRob2RJbnZva2VyLkludm9rZShPYmplY3Qgb2JqLCBJbnRQdHIqIGFyZ3MsIEJpbmRpbmdGbGFncyBpbnZva2VBdHRyKVxyXG4gICAtLS0gRW5kIG9mIGlubmVyIGV4Y2VwdGlvbiBzdGFjayB0cmFjZSAtLS1cclxuICAgYXQgU3lzdGVtLlJlZmxlY3Rpb24uTWV0aG9kSW52b2tlci5JbnZva2UoT2JqZWN0IG9iaiwgSW50UHRyKiBhcmdzLCBCaW5kaW5nRmxhZ3MgaW52b2tlQXR0cilcclxuICAgYXQgU3lzdGVtLlJlZmxlY3Rpb24uUnVudGltZU1ldGhvZEluZm8uSW52b2tlKE9iamVjdCBvYmosIEJpbmRpbmdGbGFncyBpbnZva2VBdHRyLCBCaW5kZXIgYmluZGVyLCBPYmplY3RbXSBwYXJhbWV0ZXJzLCBDdWx0dXJlSW5mbyBjdWx0dXJlKVxyXG4gICBhdCBEYWxhbXVkLlBsdWdpbi5EYWxhbXVkUGx1Z2luSW50ZXJmYWNlLkdldFBsdWdpbkNvbmZpZygpIGluIEM6XFxnb2F0c29mdFxcY29tcGFueXNlY3JldHNcXGRhbGFtdWRcXFBsdWdpblxcRGFsYW11ZFBsdWdpbkludGVyZmFjZS5jczpsaW5lIDMzOFxyXG4gICBhdCBNYXJrZXRidWRkeS5Db25maWd1cmF0aW9uLkdldE9yTG9hZCgpIGluIEM6XFxVc2Vyc1xcY2hhbGtvc1xcU29mdHdhcmVcXGZmeGl2XFxNYXJrZXRidWRkeVxcTWFya2V0YnVkZHlcXENvbmZpZ3VyYXRpb24uY3M6bGluZSA0NFxyXG4gICBhdCBNYXJrZXRidWRkeS5QbHVnaW5VSS5EcmF3T3ZlcmxheVdpbmRvdygpIGluIEM6XFxVc2Vyc1xcY2hhbGtvc1xcU29mdHdhcmVcXGZmeGl2XFxNYXJrZXRidWRkeVxcTWFya2V0YnVkZHlcXFBsdWdpblVJLmNzOmxpbmUgNDNcclxuICAgYXQgRGFsYW11ZC5VdGlsaXR5LkV2ZW50SGFuZGxlckV4dGVuc2lvbnMuSGFuZGxlSW52b2tlKEFjdGlvbiBhY3QpIGluIEM6XFxnb2F0c29mdFxcY29tcGFueXNlY3JldHNcXGRhbGFtdWRcXFV0aWxpdHlcXEV2ZW50SGFuZGxlckV4dGVuc2lvbnMuY3M6bGluZSA5NiIsIkNvbnRleHQiOiJFeGNlcHRpb24gZHVyaW5nIHJhaXNlIG9mIFwiVm9pZCBEcmF3VWkoKVwiIn0=
2023-01-16 06:21:53.224 -06:00 [ERR] Exception during raise of Void DrawUi()
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Newtonsoft.Json.JsonReaderException: Input string '1.0' is not a valid integer. Path 'UndercutPrice', line 20, position 22.
   at Newtonsoft.Json.JsonTextReader.ParseReadNumber(ReadType readType, Char firstChar, Int32 initialPosition)
   at Newtonsoft.Json.JsonTextReader.ReadNumberValue(ReadType readType)
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Dalamud.Configuration.PluginConfigurations.LoadForType[T](String pluginName) in C:\goatsoft\companysecrets\dalamud\Configuration\PluginConfigurations.cs:line 103
   at InvokeStub_PluginConfigurations.LoadForType(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Dalamud.Plugin.DalamudPluginInterface.GetPluginConfig() in C:\goatsoft\companysecrets\dalamud\Plugin\DalamudPluginInterface.cs:line 338
   at Marketbuddy.Configuration.GetOrLoad() in C:\Users\chalkos\Software\ffxiv\Marketbuddy\Marketbuddy\Configuration.cs:line 44
   at Marketbuddy.PluginUI.DrawOverlayWindow() in C:\Users\chalkos\Software\ffxiv\Marketbuddy\Marketbuddy\PluginUI.cs:line 43
   at Dalamud.Utility.EventHandlerExtensions.HandleInvoke(Action act) in C:\goatsoft\companysecrets\dalamud\Utility\EventHandlerExtensions.cs:line 96
```

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and Marketbuddy.

**Comment by xPumaa** [comment]
https://github.com/chalkos/Marketbuddy/issues/31
