### ISSUE TITLE
Market buddy does not start

### ISSUE THREAD

**Issue by StarkITA** [chalkos/Marketbuddy#46]
### What are you trying to do?

Sell stuff through retainer

### What is the expected behavior?

Being able to click the listing to undercut automatically

### What actually happened?

Sales window does not pop up, because plugin does not load properly

### Logs

```shell
16:44:53.548 INF | [PLUGINM] Loading plugin Marketbuddy
16:44:53.567 INF | [LOCALPLUGIN] Loading Marketbuddy.dll
16:44:53.583 ERR | [Marketbuddy] Error loading plugin
16:44:53.583 ERR | System.NullReferenceException: Object reference not set to an instance of an object.
16:44:53.583 ERR |    at FFXIVClientStructs.Interop.Resolver.ResolveFromCache() in D:\a\Dalamud\Dalamud\lib\FFXIVClientStructs\FFXIVClientStructs\Interop\Resolver.cs:line 151
16:44:53.583 ERR |    at FFXIVClientStructs.Interop.Resolver.Resolve() in D:\a\Dalamud\Dalamud\lib\FFXIVClientStructs\FFXIVClientStructs\Interop\Resolver.cs:line 171
16:44:53.583 ERR |    at Marketbuddy.Marketbuddy..ctor(DalamudPluginInterface pluginInterface) in C:\Users\chalkos\Software\ffxiv\Marketbuddy\Marketbuddy\Marketbuddy.cs:line 39
16:44:53.642 INF | [LOCALPLUGIN] Finished loading Marketbuddy.dll
16:44:53.643 INF | [PLUGINM] Loading plugin Market board
16:44:53.643 INF | [LOCALPLUGIN] Loading MarketBoardPlugin.dll
16:45:00.222 INF | [LOCALPLUGIN] Finished loading MarketBoardPlugin.dll
16:45:55.616 INF | [PLUGINR] Fetching repo: https://github.com/chalkos/Marketbuddy/raw/main/repo.json
16:45:56.002 INF | [PLUGINR] Successfully fetched repo: https://github.com/chalkos/Marketbuddy/raw/main/repo.json
16:47:55.448 INF | [PLUGINR] Fetching repo: https://github.com/chalkos/Marketbuddy/raw/main/repo.json
16:47:55.673 INF | [PLUGINR] Successfully fetched repo: https://github.com/chalkos/Marketbuddy/raw/main/repo.json
16:48:24.584 INF | [LOCALPLUGIN] Unloading Marketbuddy.dll
16:48:24.586 ERR | [LOCALPLUGIN] Error while unloading Marketbuddy
16:48:24.586 ERR |    at Marketbuddy.Marketbuddy.Dispose() in C:\Users\chalkos\Software\ffxiv\Marketbuddy\Marketbuddy\Marketbuddy.cs:line 68
16:48:24.588 ERR |    at Marketbuddy.Marketbuddy.Dispose() in C:\Users\chalkos\Software\ffxiv\Marketbuddy\Marketbuddy\Marketbuddy.cs:line 68
```

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and Marketbuddy.

**Comment by LTS-FFXIV** [comment]
Staging, switching back to release channel fixed it

**Comment by StarkITA** [comment]
I didn't even notice I had testing enabled. Thanks!
