### ISSUE TITLE
Plugin Does Not Load

### ISSUE THREAD

**Issue by BlitzKantern** [chalkos/Marketbuddy#50]
### What are you trying to do?

Since the update for DT, the plugin says fails to load. Restarting does not resolve.

### What is the expected behavior?

Loading

### What actually happened?

Not loading

### FFXIV Update

- [x] I have confirmed that I have the latest version of XIVLauncher and Marketbuddy.

**Comment by chalkos** [comment]
check if this fixes it https://github.com/chalkos/Marketbuddy/issues/31
it's loading fine for other people

**Comment by BlitzKantern** [comment]
Deleted configuration but it did not resolve.

Here is the error I receive:

2024-07-02 21:58:28.772 -05:00 [ERR] [LOCALPLUGIN] Exception in plugin constructor
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeLoadException: Could not load type 'HandlerDelegate' from assembly 'Dalamud, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Marketbuddy.Marketbuddy..ctor(DalamudPluginInterface pluginInterface)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeConstructorWithoutAlloc(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeConstructorWithoutAlloc(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects, IServiceScope scope) in C:\goatsoft\companysecrets\dalamud\IoC\Internal\ServiceContainer.cs:line 130
   at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Types\LocalPlugin.cs:line 429
2024-07-02 21:58:28.783 -05:00 [ERR] [LOCALPLUGIN] Error while loading Marketbuddy, failed to bind and call the plugin constructor

**Comment by BlitzKantern** [comment]
I disabled/removed and purged all folders in appdata. Reinstalled and it was resolved.
