### ISSUE TITLE
Unload Error

### ISSUE THREAD

**Issue by Solterax** [chalkos/Marketbuddy#56]
### What are you trying to do?

I often disable plugins when doing any content due to wanting to remove any impact on my actual gameplay but since 7.1 when I disable Marketbuddy it fails to unload and then sits in an errored state until I restart my game. I don't seem to have an issue with any other plugins having this problem and have seen a log only from Marketbuddy regarding this. 

### What is the expected behavior?

Correctly unload and reload the plugin when desired

### What actually happened?

Unload error on disabling the plugin

### Logs

```shell
05:58:02.697 | ERR | [LOCALPLUGIN] "Marketbuddy"(f4c38882-bbb5-4c2f-90cf-815a8467e59c): Failed to dispose "instance"
	System.MissingMethodException: Method not found: 'Void Dalamud.Plugin.Ipc.ICallGateProvider`2.UnregisterFunc()'.
	   at Marketbuddy.IPCManager.Shutdown()
	   at Marketbuddy.Marketbuddy.Dispose() in C:\Users\chalkos\Software\ffxiv\Marketbuddy\Marketbuddy\Marketbuddy.cs:line 62
	   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	--- End of stack trace from previous location ---
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
	--- End of stack trace from previous location ---
	   at Dalamud.Plugin.Internal.Types.LocalPlugin.<>c.<<ClearAndDisposeAllResources>b__78_4>d.MoveNext() in C:\goatsoft\companysecrets\dalamud\\Plugin\Internal\Types\LocalPlugin.cs:line 681
	--- End of stack trace from previous location ---
	   at Dalamud.Plugin.Internal.Types.LocalPlugin.<>c__DisplayClass78_0.<<ClearAndDisposeAllResources>g__AttemptCleanup|3>d`2.MoveNext() in C:\goatsoft\companysecrets\dalamud\\Plugin\Internal\Types\LocalPlugin.cs:line 745
05:58:03.713 | ERR | [LOCALPLUGIN] Error while unloading "Marketbuddy"
	System.AggregateException: One or more errors occurred. (Method not found: 'Void Dalamud.Plugin.Ipc.ICallGateProvider`2.UnregisterFunc()'.)
	 ---> System.MissingMethodException: Method not found: 'Void Dalamud.Plugin.Ipc.ICallGateProvider`2.UnregisterFunc()'.
	   at Marketbuddy.IPCManager.Shutdown()
	   at Marketbuddy.Marketbuddy.Dispose() in C:\Users\chalkos\Software\ffxiv\Marketbuddy\Marketbuddy\Marketbuddy.cs:line 62
	   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	--- End of stack trace from previous location ---
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
	--- End of stack trace from previous location ---
	   at Dalamud.Plugin.Internal.Types.LocalPlugin.<>c.<<ClearAndDisposeAllResources>b__78_4>d.MoveNext() in C:\goatsoft\companysecrets\dalamud\\Plugin\Internal\Types\LocalPlugin.cs:line 681
	--- End of stack trace from previous location ---
	   at Dalamud.Plugin.Internal.Types.LocalPlugin.<>c__DisplayClass78_0.<<ClearAndDisposeAllResources>g__AttemptCleanup|3>d`2.MoveNext() in C:\goatsoft\companysecrets\dalamud\\Plugin\Internal\Types\LocalPlugin.cs:line 745
	   --- End of inner exception stack trace ---
	   at Dalamud.Plugin.Internal.Types.LocalPlugin.ClearAndDisposeAllResources(PluginLoaderDisposalMode disposalMode) in C:\goatsoft\companysecrets\dalamud\\Plugin\Internal\Types\LocalPlugin.cs:line 729
	   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
	   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
	   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
	   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
	   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
	   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
	   at Dalamud.Plugin.Internal.Types.LocalPlugin.<>c__DisplayClass78_0.<<ClearAndDisposeAllResources>g__AttemptCleanup|3>d`2.MoveNext() in C:\goatsoft\companysecrets\dalamud\\Plugin\Internal\Types\LocalPlugin.cs:line 761
	   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
	   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
	   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
	   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
	   at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder.SetResult()
	   at Dalamud.Plugin.Internal.Types.LocalPlugin.<>c.<<ClearAndDisposeAllResources>b__78_2>d.MoveNext() in C:\goatsoft\companysecrets\dalamud\\Plugin\Internal\Types\LocalPlugin.cs:line 726
	   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
	   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
	   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
	   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
	   at System.Threading.Tasks.Task.DelayPromise.CompleteTimedOut()
	   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
	   at System.Threading.TimerQueue.FireNextTimers()
	   at System.Threading.ThreadPoolWorkQueue.Dispatch()
	   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
	--- End of stack trace from previous location ---
	   at Dalamud.Plugin.Internal.Types.LocalPlugin.UnloadAsync(PluginLoaderDisposalMode disposalMode) in C:\goatsoft\companysecrets\dalamud\\Plugin\Internal\Types\LocalPlugin.cs:line 471
05:58:03.713 | ERR | [PLUGINW] Plugin installer threw an unexpected error
	System.AggregateException: One or more errors occurred. (Method not found: 'Void Dalamud.Plugin.Ipc.ICallGateProvider`2.UnregisterFunc()'.)
	 ---> System.MissingMethodException: Method not found: 'Void Dalamud.Plugin.Ipc.ICallGateProvider`2.UnregisterFunc()'.
	   at Marketbuddy.IPCManager.Shutdown()
	   at Marketbuddy.Marketbuddy.Dispose() in C:\Users\chalkos\Software\ffxiv\Marketbuddy\Marketbuddy\Marketbuddy.cs:line 62
	   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	--- End of stack trace from previous location ---
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
	--- End of stack trace from previous location ---
	   at Dalamud.Plugin.Internal.Types.LocalPlugin.<>c.<<ClearAndDisposeAllResources>b__78_4>d.MoveNext() in C:\goatsoft\companysecrets\dalamud\\Plugin\Internal\Types\LocalPlugin.cs:line 681
	--- End of stack trace from previous location ---
	   at Dalamud.Plugin.Internal.Types.LocalPlugin.<>c__DisplayClass78_0.<<ClearAndDisposeAllResources>g__AttemptCleanup|3>d`2.MoveNext() in C:\goatsoft\companysecrets\dalamud\\Plugin\Internal\Types\LocalPlugin.cs:line 745
	   --- End of inner exception stack trace ---
	   at Dalamud.Plugin.Internal.Types.LocalPlugin.ClearAndDisposeAllResources(PluginLoaderDisposalMode disposalMode) in C:\goatsoft\companysecrets\dalamud\\Plugin\Internal\Types\LocalPlugin.cs:line 729
	   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
	   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
	   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
	   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
	   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
	   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
	   at Dalamud.Plugin.Internal.Types.LocalPlugin.<>c__DisplayClass78_0.<<ClearAndDisposeAllResources>g__AttemptCleanup|3>d`2.MoveNext() in C:\goatsoft\companysecrets\dalamud\\Plugin\Internal\Types\LocalPlugin.cs:line 761
	   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
	   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
	   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
	   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
	   at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder.SetResult()
	   at Dalamud.Plugin.Internal.Types.LocalPlugin.<>c.<<ClearAndDisposeAllResources>b__78_2>d.MoveNext() in C:\goatsoft\companysecrets\dalamud\\Plugin\Internal\Types\LocalPlugin.cs:line 726
	   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
	   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
	   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
	   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
	   at System.Threading.Tasks.Task.DelayPromise.CompleteTimedOut()
	   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
	   at System.Threading.TimerQueue.FireNextTimers()
	   at System.Threading.ThreadPoolWorkQueue.Dispatch()
	   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
	--- End of stack trace from previous location ---
	   at Dalamud.Plugin.Internal.Types.LocalPlugin.UnloadAsync(PluginLoaderDisposalMode disposalMode) in C:\goatsoft\companysecrets\dalamud\\Plugin\Internal\Types\LocalPlugin.cs:line 471
	   at Dalamud.Interface.Internal.Windows.PluginInstaller.PluginInstallerWindow.<>c__DisplayClass109_3.<<DrawPluginControlButton>b__8>d.MoveNext() in C:\goatsoft\companysecrets\dalamud\\Interface\Internal\Windows\PluginInstaller\PluginInstallerWindow.cs:line 3088
```

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and Marketbuddy.

**Comment by Breegasm** [comment]
This is still happening

**Comment by Battler624** [comment]
Can confirm same thing, if I disable a collection that has marketbuddy in it and re-enable it, it would give me the unload error.

**Comment by AliciaMacdonald** [comment]
This is still happening for me too. Additionally, marketbuddy is making all my NPC dialogue laboriously slow. Once I unload it, the game plays much faster with any sort of NPC popups like cactpot, vendors, repairs, etc. even though it fails to unload properly.

@chalkos if you're busy maybe the rest of us should try looking into fixing it? I've never done ffxiv modding but I do work as a ml software dev

**Comment by chalkos** [comment]
I'm not playing right now, so if someone wants to submit a PR for this, feel free

**Comment by chalkos** [comment]
@Limiana if you can, would you mind checking if this is related to your IPC code?

**Comment by Limiana** [comment]
> [@Limiana](https://github.com/Limiana) if you can, would you mind checking if this is related to your IPC code?

Just recompiling the plugin with most recent Dalamud version should do the trick, there were some internal changes

**Comment by chalkos** [comment]
should be fixed now 9b939b350f4a75095aff2ef5952f0dda7c9fa161
